#define TRUE 1
#define FALSE 0

#define ERROR_EXIT -1
#define ERROR_EXPECTED_MORE_ARGUMENTS -2
#define ERROR_EXPECTED_LESS_ARGUMENTS -3
#define ERROR_COULD_NOT_FIND_SPACE -1
#define ERROR_COULD_NOT_ALLOCATE -4
#define ERROR_NOT_AN_INTEGER -5
#define ERROR_NOT_A_STRING -6
#define ERROR_LABEL_DEFINED -7
#define ERROR_INSTRUCTION_DOES_NOT_EXIST -8
#define ERROR_NOT_A_PARAMETER -9
#define ERROR_INVALID_ADDRESSING_METHOD -10
#define ERROR_LABEL_DOES_NOT_EXIST -11
#define ERROR_COULD_NOT_OPEN_FILE -12
#define SUCCESS 1

#define WORD_LEN 14
#define MAX_LABEL_LEN 30
#define MEM_START_POS 100
#define MAX_LINE_LENGTH 81

void printStatus(int);
void printLineStatus(int, int);
